### ISSUE TITLE
Change the "Sample Frequency" Label In the Data Plotting Window

### ISSUE THREAD

**Issue by juchong** [juchong/iSensor-ADcmXL-FX3Gui#15]
It's unclear whether "Sample Frequency" refers to the IMU sample frequency (decimation setting) or the Windows form update rate. Maybe we can change it to "Plot Update Rate"?

**Comment by ajn96** [comment]
Done: https://github.com/analogdevicesinc/iSensor-FX3-Eval/commit/1090c39aa8b3b0a36a5bf7aa9bab01fcbe41ec12
