### ISSUE TITLE
Add Data Ready Configuration To The Data Plotting Form

### ISSUE THREAD

**Issue by juchong** [juchong/iSensor-ADcmXL-FX3Gui#16]
It's sometimes useful to enable/disable DRActive when using the Data Plotting form.

**Comment by ajn96** [comment]
@juchong What is the rationale for this? The data plotter reads one set of regs at a time, it does not make use of the data streaming. DR active will just make sure that all the data for a given plot point comes from a single IMU sample.

Worth noting that enabling DR active while there is no DR or if the DR is slower than the plotter sample rate will cause some undesirable behavior

**Comment by juchong** [comment]
After thinking through this, I also agree that this change might cause more issues than it solves. Ultimately the display rate is determined by the Windows form and has nothing to do with the IMU. I think it's best to abandon this approach.
