### ISSUE TITLE
Add reasonable default scale values to all regmaps

### ISSUE THREAD

**Issue by ajn96** [juchong/iSensor-ADcmXL-FX3Gui#17]
Scale can be set by user for the plotting forms, or manually adjusted in the regmap. Would be easier if there were default scales already set.

For IMU families with multiple ranges, will have to use judgement regarding what to set the scale values too. Could potentially break out each part in the personality file list - might get cluttered though.

**Comment by juchong** [comment]
Most (recent) IMUs share the same scale factors, so it may be reasonable to assign a set of "known variant register labels" similar to what's already done for the USR_SCR_1 register to decode. My concern with assigning a scale factor other than 1 for unknown devices is that it may cause more confusion. 

Another approach might be to assign a sub-variant to the device selector. The user would then have to select the correct device variant.

**Comment by ajn96** [comment]
TODO: Update wiki to include description of the register format (raw digital data).

**Comment by ajn96** [comment]
Done
