### ISSUE TITLE
ADIS16505 Data Logging

### ISSUE THREAD

**Issue by ajn96** [juchong/iSensor-ADcmXL-FX3Gui#22]
Dear @juchong and @ajn96 
I bought MEMS IMU Adis-16505 together with Eval-adis-fx3. I make the sensor vibrate through a shaker in the X direction with a constant frequency and amplitude. This is an experiment to read the output of x, y, z from the accelerometer. What is important to me is the amplitude and frequency in the time domain. The frequency domain simulation is successful, but the time domain simulation is not clear. When I simulate the time domain I don't get the correct frequency and amplitude. Maybe it has to do with the sample rate? I do not know. Please let me know if you want csv files for more information to help me out.

I still tried to read the frequency domain of X, Y, Z ACCL_OUT in matlab, it worked, but the time domain is still not clear to me. Can you help me to read the amplitude and frequency of the time domain in matlab or on the Eval-adis-fx3 app v2.9.4.0.

_Originally posted by @mokhtarpakazizi in https://github.com/analogdevicesinc/iSensor-FX3-API/issues/9#issuecomment-822215128_

**Comment by ajn96** [comment]
Hi @mokhtarpakazizi,

Moving the issue over to the EVAL GUI repo.

Using the EVAL-ADIS-FX3 app you can plot time domain data using the data plotter GUI. This data will be plotted in LSBs, which then must be scaled to the desired units. This allows for a quick view of the time series output of the device, but the data is not synchronous to the Fs of the sensor.

For what you are doing you should use the register logging form to log data ready synchronous data. This data (as a CSV) can then be post-processed in excel, matlab, etc.

See user guide here for instructions using the data logger:
https://wiki.analog.com/resources/eval/user-guides/inertial-mems/evaluation-systems/eval-adis-fx3-eval-user-guide

Thanks,
Alex

**Comment by mokhtarpakazizi** [comment]
Hi @ajn96 
Thanks for your response.
I totally agree with you. this process what you mentioned I have all done. for example, the accelerometer's X direction output is X_ACCL_LOW and X_ACCL_OUT. what is not clear to me is the unit of the amplitude in the time domain. For example at X_ACCL_OUT, I get 318 to -185 peak to peak.

 how do you convert this value into, for example, m/s or g or voltage?

**Comment by ajn96** [comment]
Hi,

The register values are unscaled - just the raw digital output of the IMU.

Table 1 of the ADIS16505 datasheet lists scale factors to convert the LSB outputs to SI units:
https://www.analog.com/media/en/technical-documentation/data-sheets/adis16505.pdf

For example for the 16-bit accel outputs ([X/Y/Z]_ACCL_OUT):

318LSBs / ((26,756,268 >> 16) LSBs/(m/s^2)) = 0.779m/s^2

If you have additional questions about the functionality of the sensor itself, the folks over at engineer zone should be able to help.
https://ez.analog.com/mems

**Comment by mokhtarpakazizi** [comment]
Hi @ajn96 ,
that's what i'm looking for. thank you very much for your useful information. that is clear to me

**Comment by ajn96** [comment]
Glad I could help.
-Alex
