### ISSUE TITLE
IMU Burst (or Register) Data Logging - Record Time Input

### ISSUE THREAD

**Issue by NevadaMark** [juchong/iSensor-ADcmXL-FX3Gui#35]
Could we consider accommodating a time input OR a total number of samples input, with respect to how customers will establish total record time? 

![image](https://user-images.githubusercontent.com/12829744/176256818-ca54542f-d05f-4abb-9910-9e2b320169b4.png)

![image](https://user-images.githubusercontent.com/12829744/176257011-e78510cd-3f3a-48b5-a84c-b3ba167d567b.png)

Also, should the Burst mode have the same options as the Register Logging?

**Comment by ajn96** [comment]
Both the burst mode and the register logger use the same underlying file logging utility. It would be fairly simple to modify this utility to append a timestamp for when each sample is written to the file. Note, this would have some latency wrt to the real inertial data sample time (delay for data transmission over USB, post-processing time, etc) - would likely see "groups" of samples processed at similar periodic intervals, based on the USB packet size. 

It would be technically feasible to also log the sample time (wrt to start of SPI transfer/data ready edge), but that would take more development work, since it requires modification to the EVAL-ADIS-FX3 firmware.

**Comment by ajn96** [comment]
![image](https://user-images.githubusercontent.com/35480179/176454814-ad9c50dc-8d53-4d50-8576-3894eb2acf28.png)
I added the ability to log the USB packet time (hours, min, sec, ms), as well as the file write time, to each data log file

**Comment by NevadaMark** [comment]
Thank you! I am sorry that it took me so long to get back to this.  I really appreciate this, but  I fear that I may have not been clear in what I was looking for.  My intention was to ask if we could add a **total record time**, in the Window, to help users select the number of burst reads.  For example, if I select 10000 reads and the ODR (based on decimation filter setting) is 100Hz, the total record time would be 100 seconds.  For me, it is not hard to imagine that information being helpful for someone, who just needs some quick feedback on the length of time.  Thoughts? 

As a side note, we have had customers ask for a time stamp, with each data sample, but I have resisted this, since previous eavl platforms could not support it, without affecting latency and in the worst cases, even the update rates.  On that idea, I trust your judgement on whether that is a worthwhile option....but will also give it more thought and be aware as I work on new cases that could value this. 

Thank you!!!

**Comment by ajn96** [comment]
Gotcha, I did misunderstand the original ask. Adding a record time control is straightforward - the application already checks the data ready frequency to ensure that the requested SPI traffic will fit into a single data ready valid interval. I can add an estimate of the log time based on this.

Timestamping each sample would be technically feasible, but require some work to accomplish. The FX3 firmware keeps track of the current UTC time with ms granularity, and it would be possible to append a 32-bit 10MHz timestamp value to each sample without significant overhead. The primary difficulty is that this requires changing the USB message format significantly, as well as the way buffers are received and passed to application code. So long story short, the hardware could support accurate sample timestamping (from the firmware side), but any "quick" implementation would be somewhat hacky, and a clean implementation would require significant development effort.

**Comment by NevadaMark** [comment]
Thank you!

**Comment by ajn96** [comment]
This has been implemented. The form now supports record time inputs for synchronous captures, and the data logs also contain the USB packet timestamp for each sample.

See: https://github.com/analogdevicesinc/iSensor-FX3-Eval/releases/tag/v2.9.5.7-pub
