### ISSUE TITLE
Running data plot and FFT plot simultaneously causes lock-up / crash

### ISSUE THREAD

**Issue by ghost** [juchong/iSensor-ADcmXL-FX3Gui#6]
Running an FFT plot and time domain plot at the same time causes unstable GUI behavior. This is due to the fairly heavy resource utilization on the FX3 by the FFT plot GUI (has to capture continuous, data ready synchronized data) conflicting with the data plot GUI. This can be avoided by stopping any time domain data plot before running an FFT plot, and vice versa.

This may eventually be fixed via re-work of the resource protection scheme in use on the FX3 API. The stream mutex approach currently implemented isn't perfect.

**Comment by ajn96** [comment]
Was resolved by adding logic to FFT plotting GUI which automatically pauses any other "background" forms that might be communicating with the FX3
